name             'chefapi_chef_server'
maintainer       'Mark Gibbons'
license          'Apache-2.0'
description      'Demonstrate the chef server api applications'
version          '0.1.0'
chef_version     '>= 13'
depends          'chef-server'
